#!/bin/bash

#
# Generates new static content and deploys it to gh-pages branch
#

set -eu

pushd public

git checkout .
git pull

popd

hugo

pushd public

git add .
git commit -m "$(date) deployment"
git push

popd
